### ISSUE TITLE
Unable to compile on Ubuntu 13.10 - 'CAstNativeFunctionLiteral' was not declared in this scope.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhongzi253/pyv8#209]
```
What steps will reproduce the problem?
svn checkout v8
svn checkout pyv8
building v8 succeeds
sudo V8_HOME=/home/david/v8 python setup.py install

gcc hangs on src/AST.h:
-----------------------
In file included from src/Engine.cpp:12:0:
src/AST.h: At global scope:
src/AST.h:746:64: error: expected ‘)’ before ‘*’ token
   CAstSharedFunctionInfoLiteral(v8i::SharedFunctionInfoLiteral *func) : CAstExpression(func) {}

                                                                ^
src/AST.h: In member function ‘virtual void 
CAstVisitor::VisitNativeFunctionLiteral(v8::internal::NativeFunctionLiteral*)’
:
src/AST.h:767:42: error: ‘CAstNativeFunctionLiteral’ was not declared in 
this scope
       callback(py::object(CAst##type(node))); }; } }

                                          ^
/home/david/v8/src/ast.h:100:3: note: in expansion of macro ‘DECLARE_VISIT’
   V(NativeFunctionLiteral)                      \
   ^
/home/david/v8/src/ast.h:124:3: note: in expansion of macro 
‘EXPRESSION_NODE_LIST’
   EXPRESSION_NODE_LIST(V)
   ^
src/AST.h:769:3: note: in expansion of macro ‘AST_NODE_LIST’
   AST_NODE_LIST(DECLARE_VISIT)

   ^
src/AST.h: In member function ‘virtual void 
CAstObjectCollector::VisitNativeFunctionLiteral(v8::internal::NativeFunctionLite
ral*)’:
src/AST.h:784:107: error: ‘CAstNativeFunctionLiteral’ was not declared in 
this scope
 #define DECLARE_VISIT(type) virtual void Visit##type(v8i::type* node) { m_obj = py::object(CAst##type(node)); }

                                                                                                           ^
/home/david/v8/src/ast.h:100:3: note: in expansion of macro ‘DECLARE_VISIT’
   V(NativeFunctionLiteral)                      \
   ^
/home/david/v8/src/ast.h:124:3: note: in expansion of macro 
‘EXPRESSION_NODE_LIST’
   EXPRESSION_NODE_LIST(V)
   ^
src/AST.h:785:3: note: in expansion of macro ‘AST_NODE_LIST’
   AST_NODE_LIST(DECLARE_VISIT)

   ^
src/AST.h: In member function ‘virtual void 
CAstListCollector::VisitNativeFunctionLiteral(v8::internal::NativeFunctionLitera
l*)’:
src/AST.h:811:114: error: ‘CAstNativeFunctionLiteral’ was not declared in 
this scope
 #define DECLARE_VISIT(type) virtual void Visit##type(v8i::type* node) { m_nodes.append(py::object(CAst##type(node))); }

                                                                                                                  ^
/home/david/v8/src/ast.h:100:3: note: in expansion of macro ‘DECLARE_VISIT’
   V(NativeFunctionLiteral)                      \
   ^
/home/david/v8/src/ast.h:124:3: note: in expansion of macro 
‘EXPRESSION_NODE_LIST’
   EXPRESSION_NODE_LIST(V)
   ^
src/AST.h:812:3: note: in expansion of macro ‘AST_NODE_LIST’
   AST_NODE_LIST(DECLARE_VISIT)

   ^
error: command 'i686-linux-gnu-gcc' failed with exit status 1

What is the expected output? What do you see instead?
Expect it to compile.

What version of the product are you using? On what operating system?
PyV8 r549  Ubuntu 13.10

Please provide any additional information below.

gcc (Ubuntu/Linaro 4.8.1-10ubuntu4) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Original issue reported on code.google.com by `dstephen...@gmail.com` on 3 Oct 2013 at 6:43
