### ISSUE TITLE
src/Context.h:66:114: error: no member named 'HasOutOfMemoryException' in 'v8::Context'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhongzi253/pyv8#236]
```
What steps will reproduce the problem?
1. Build on OSX 10.9

What is the expected output? What do you see instead?
Build failed.

INFO: Found Google v8 base on V8_HOME </Users/myhome/Downloads/v8/>
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to PyV8.egg-info/requires.txt
writing PyV8.egg-info/PKG-INFO
writing top-level names to PyV8.egg-info/top_level.txt
writing dependency_links to PyV8.egg-info/dependency_links.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'PyV8.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-intel/egg
running install_lib
running build_py
running build_ext
building '_PyV8' extension
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common 
-fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall 
-Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall 
-Wstrict-prototypes -DENABLE_DTRACE -pipe -arch x86_64 
-DBOOST_PYTHON_STATIC_LIB -DV8_NATIVE_REGEXP -DENABLE_DEBUGGER_SUPPORT 
-DV8_TARGET_ARCH_X64 -I/Users/myhome/Downloads/v8/include 
-I/Users/myhome/Downloads/v8/ -I/Users/myhome/Downloads/v8/src 
-I/opt/local/include -I/usr/local/include 
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c 
src/Utils.cpp -o build/temp.macosx-10.9-intel-2.7/src/Utils.o -g -O3 
-Wdeprecated-writable-strings -stdlib=libc++
In file included from src/Utils.cpp:11:
In file included from src/Locker.h:4:
src/Context.h:66:114: error: no member named 'HasOutOfMemoryException' in 
'v8::Context'
  bool HasOutOfMemoryException(void) { v8::HandleScope handle_scope(v8::Isolate::GetCurrent()); return Handle()->HasOutOfMemoryException(); }
                                                                                                       ~~~~~~~~  ^
In file included from src/Utils.cpp:12:
src/V8Internal.h:11:10: fatal error: 'src/platform.h' file not found
#include "src/platform.h"
         ^
2 errors generated.
error: command 'cc' failed with exit status 1

Any idea on how to make it work?

Thanks
Pascal.
```

Original issue reported on code.google.com by `pvantrep...@gmail.com` on 7 Aug 2014 at 12:14
