### ISSUE TITLE
Complie error on Ubuntu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhongzi253/pyv8#90]
```
What steps will reproduce the problem?
1. Trying to build on Ubuntu 10.04 with trunk builds from boost, v8, and pyv8
2. running `python setup.py build`

What is the expected output? What do you see instead?

A report of a successful build.

Actual output:

In file included from src/Engine.cpp:36:
src/AST.h:282: error: expected ‘)’ before ‘*’ token
src/AST.h: In member function ‘boost::python::api::object 
CAstWithEnterStatement::expression() const’:
src/AST.h:284: error: ‘WithEnterStatement’ is not a member of ‘v8i’
src/AST.h:284: error: ‘WithEnterStatement’ is not a member of ‘v8i’
src/AST.h:284: error: no matching function for call to 
‘CAstWithEnterStatement::as() const’
src/AST.h: In member function ‘bool CAstWithEnterStatement::is_catch_block() 
const’:
src/AST.h:286: error: ‘WithEnterStatement’ is not a member of ‘v8i’
src/AST.h:286: error: ‘WithEnterStatement’ is not a member of ‘v8i’
src/AST.h:286: error: no matching function for call to 
‘CAstWithEnterStatement::as() const’
src/AST.h: At global scope:
src/AST.h:292: error: expected ‘)’ before ‘*’ token
src/AST.h:438: error: expected ‘)’ before ‘*’ token
src/AST.h: In member function ‘virtual void 
CAstVisitor::VisitEnterWithContextStatement(v8::internal::EnterWithContextStatem
ent*)’:
src/AST.h:634: error: ‘CAstEnterWithContextStatement’ was not declared in 
this scope
src/AST.h: In member function ‘virtual void 
CAstVisitor::VisitExitContextStatement(v8::internal::ExitContextStatement*)’:
src/AST.h:634: error: ‘CAstExitContextStatement’ was not declared in this 
scope
src/AST.h: In member function ‘virtual void 
CAstObjectCollector::VisitEnterWithContextStatement(v8::internal::EnterWithConte
xtStatement*)’:
src/AST.h:644: error: ‘CAstEnterWithContextStatement’ was not declared in 
this scope
src/AST.h: In member function ‘virtual void 
CAstObjectCollector::VisitExitContextStatement(v8::internal::ExitContextStatemen
t*)’:
src/AST.h:644: error: ‘CAstExitContextStatement’ was not declared in this 
scope
src/AST.h: In member function ‘virtual void 
CAstListCollector::VisitEnterWithContextStatement(v8::internal::EnterWithContext
Statement*)’:
src/AST.h:665: error: ‘CAstEnterWithContextStatement’ was not declared in 
this scope
src/AST.h: In member function ‘virtual void 
CAstListCollector::VisitExitContextStatement(v8::internal::ExitContextStatement*
)’:
src/AST.h:665: error: ‘CAstExitContextStatement’ was not declared in this 
scope
src/AST.h: In member function ‘CAstVariableProxy 
CAstTryCatchStatement::GetCatchVariable() const’:
src/AST.h:753: error: ‘class v8::internal::TryCatchStatement’ has no member 
named ‘catch_var’

What version of the product are you using? On what operating system?

Linux ubuntu 2.6.32-26-generic (Lucid)
Building svn r373
```

Original issue reported on code.google.com by `tes...@gmail.com` on 16 Jun 2011 at 6:18
