### ISSUE TITLE
Unable to compile on Ubuntu 12.04 - ‘CAstYield’ was not declared in this scope

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhongzi253/pyv8#168]
```
What steps will reproduce the problem?
1. svn checkout v8
2. svn checkout pyv8
3. building v8 succeeds
4. for some reason, python 3.2 can't get V8_HOME env variable - editing the 
source of setup.py and hardcoding it solves that step
5. sudo python3.2 setup.py install

gcc hangs on src/AST.h:
-----------------------
In file included from src/Engine.cpp:14:0:

src/AST.h: In member function ‘virtual void 
CAstVisitor::VisitYield(v8::internal::Yield*)’:

src/AST.h:739:3: error: ‘CAstYield’ was not declared in this scope

src/AST.h: In member function ‘virtual void 
CAstObjectCollector::VisitYield(v8::internal::Yield*)’:

src/AST.h:755:3: error: ‘CAstYield’ was not declared in this scope

src/AST.h: In member function ‘virtual void 
CAstListCollector::VisitYield(v8::internal::Yield*)’:

src/AST.h:782:3: error: ‘CAstYield’ was not declared in this scope
-----------------------

What is the expected output? What do you see instead?
I expect it to finish happily and to be able to use PyV8. Instead I see two 
hours of frustration behind me.

What version of the product are you using? On what operating system?
PyV8 r509

Please provide any additional information below.

```

Original issue reported on code.google.com by `sans.ran...@gmail.com` on 4 Apr 2013 at 5:49
